# Starter set of common name kanji. Expand to cover user's actual names.
KANJI: dict[str, dict] = {
    "大": {"strokes": 3,  "meanings": ["偉大", "広がり", "包容力"], "personality": ["リーダー", "大局観"]},
    "小": {"strokes": 3,  "meanings": ["繊細", "丁寧", "細やか"], "personality": ["観察力", "気配り"]},
    "山": {"strokes": 3,  "meanings": ["安定", "堅実", "不動"],   "personality": ["信頼感", "忍耐"]},
    "川": {"strokes": 3,  "meanings": ["流れ", "柔軟", "変化"],   "personality": ["適応力", "感受性"]},
    "田": {"strokes": 5,  "meanings": ["豊か", "実り", "大地"],   "personality": ["誠実", "勤勉"]},
    "中": {"strokes": 4,  "meanings": ["中心", "バランス", "調和"],"personality": ["調停力", "公平"]},
    "木": {"strokes": 4,  "meanings": ["成長", "生命", "自然"],   "personality": ["向上心", "柔軟"]},
    "水": {"strokes": 4,  "meanings": ["流れ", "清潔", "浄化"],   "personality": ["知性", "直感"]},
    "火": {"strokes": 4,  "meanings": ["情熱", "エネルギー", "変革"],"personality": ["行動力", "カリスマ"]},
    "金": {"strokes": 8,  "meanings": ["繁栄", "輝き", "価値"],   "personality": ["決断力", "成功"]},
    "子": {"strokes": 3,  "meanings": ["純粋", "子孫", "可愛らしさ"],"personality": ["愛されキャラ", "親しみ"]},
    "花": {"strokes": 7,  "meanings": ["美", "華やか", "開花"],   "personality": ["魅力", "社交性"]},
    "愛": {"strokes": 13, "meanings": ["愛情", "温かさ", "絆"],   "personality": ["思いやり", "共感力"]},
    "美": {"strokes": 9,  "meanings": ["美しさ", "調和", "感性"], "personality": ["審美眼", "創造性"]},
    "春": {"strokes": 9,  "meanings": ["希望", "新生", "躍動"],   "personality": ["明るさ", "前向き"]},
    "夏": {"strokes": 10, "meanings": ["活力", "情熱", "輝き"],   "personality": ["エネルギッシュ", "積極的"]},
    "秋": {"strokes": 9,  "meanings": ["実り", "成熟", "深み"],   "personality": ["思慮深さ", "完成度"]},
    "冬": {"strokes": 5,  "meanings": ["静寂", "内省", "蓄積"],   "personality": ["集中力", "忍耐"]},
    "陽": {"strokes": 12, "meanings": ["明るさ", "温もり", "活力"],"personality": ["ポジティブ", "社交的"]},
    "光": {"strokes": 6,  "meanings": ["輝き", "希望", "道"],     "personality": ["理想主義", "先見性"]},
    "明": {"strokes": 8,  "meanings": ["知性", "明晰", "正直"],   "personality": ["論理的", "誠実"]},
    "真": {"strokes": 10, "meanings": ["真実", "誠実", "本質"],   "personality": ["誠実さ", "純粋"]},
    "優": {"strokes": 17, "meanings": ["優しさ", "思いやり", "品格"],"personality": ["協調性", "上品"]},
    "健": {"strokes": 11, "meanings": ["健康", "強さ", "活力"],   "personality": ["行動力", "生命力"]},
    "翔": {"strokes": 12, "meanings": ["飛翔", "自由", "可能性"], "personality": ["チャレンジ精神", "自由"]},
    "桜": {"strokes": 10, "meanings": ["美", "生命", "再生"],     "personality": ["魅力", "感受性"]},
    "葵": {"strokes": 12, "meanings": ["向上", "太陽", "成長"],   "personality": ["向上心", "明朗"]},
    "蓮": {"strokes": 13, "meanings": ["清潔", "高潔", "再生"],   "personality": ["清廉さ", "精神性"]},
    "奏": {"strokes": 9,  "meanings": ["調和", "音楽", "伝える"], "personality": ["表現力", "協調性"]},
    "凛": {"strokes": 15, "meanings": ["気品", "凛々しさ", "意志"],"personality": ["芯の強さ", "気高さ"]},
    "心": {"strokes": 4,  "meanings": ["心", "感情", "思いやり"], "personality": ["共感力", "繊細さ"]},
    "空": {"strokes": 8,  "meanings": ["自由", "広大", "無限"],   "personality": ["自由精神", "大らかさ"]},
    "海": {"strokes": 9,  "meanings": ["深さ", "広大", "包容力"], "personality": ["包容力", "神秘性"]},
    "風": {"strokes": 9,  "meanings": ["変化", "自由", "伝達"],   "personality": ["変化適応", "コミュニケーション"]},
    "星": {"strokes": 9,  "meanings": ["輝き", "目標", "希望"],   "personality": ["理想追求", "個性"]},
    "月": {"strokes": 4,  "meanings": ["神秘", "変化", "感性"],   "personality": ["直感", "芸術性"]},
    "太": {"strokes": 4,  "meanings": ["偉大", "豊か", "大らか"], "personality": ["おおらかさ", "包容力"]},
    "幸": {"strokes": 8,  "meanings": ["幸福", "恵み", "喜び"],   "personality": ["幸運体質", "感謝"]},
    "希": {"strokes": 7,  "meanings": ["希望", "珍しさ", "望み"], "personality": ["希望力", "独自性"]},
    "咲": {"strokes": 9,  "meanings": ["開花", "笑顔", "活発"],   "personality": ["明るさ", "親しみやすさ"]},
    "彩": {"strokes": 11, "meanings": ["色彩", "個性", "豊か"],   "personality": ["表現力", "多才"]},
    "結": {"strokes": 12, "meanings": ["縁", "絆", "まとめる"],   "personality": ["人脈", "まとめ役"]},
    "莉": {"strokes": 10, "meanings": ["ジャスミン", "清楚", "香り"],"personality": ["清楚", "繊細"]},
    "菜": {"strokes": 11, "meanings": ["自然", "生命力", "素直"], "personality": ["素直さ", "自然体"]},
    "里": {"strokes": 7,  "meanings": ["故郷", "温かさ", "安らぎ"],"personality": ["家族愛", "安定"]},
    "那": {"strokes": 7,  "meanings": ["美しさ", "優雅", "遠い"],  "personality": ["優雅さ", "個性"]},
    "穂": {"strokes": 15, "meanings": ["実り", "豊か", "成長"],   "personality": ["粘り強さ", "充実"]},
    "楓": {"strokes": 13, "meanings": ["変化", "美しさ", "季節"], "personality": ["変化対応", "美的感覚"]},
    "朱": {"strokes": 6,  "meanings": ["情熱", "生命力", "赤"],   "personality": ["情熱的", "行動力"]},
    "悠": {"strokes": 11, "meanings": ["ゆったり", "永遠", "深さ"],"personality": ["ゆとり", "深い思考"]},
    # 追加：2025年生まれ名前ランキング上位の名前に対応
    "湊": {"strokes": 12, "meanings": ["港", "人が集う", "安らぎ"], "personality": ["包容力", "求心力"]},
    "朔": {"strokes": 10, "meanings": ["新月", "始まり", "再生"],   "personality": ["新しい挑戦", "始まりの力"]},
    "翠": {"strokes": 14, "meanings": ["深緑", "宝石", "気品"],     "personality": ["気品", "清らかさ"]},
    "紬": {"strokes": 11, "meanings": ["織物", "丈夫", "温かみ"],   "personality": ["粘り強さ", "温かさ"]},
    "茉": {"strokes": 8,  "meanings": ["ジャスミン", "香り", "清楚"],"personality": ["清楚さ", "上品"]},
    "白": {"strokes": 5,  "meanings": ["純粋", "潔白", "始まり"],   "personality": ["誠実さ", "潔さ"]},
    "詩": {"strokes": 13, "meanings": ["詩情", "表現", "美しい言葉"],"personality": ["表現力", "豊かな感性"]},
}


def get_kanji_data(char: str) -> dict:
    """Returns kanji data. Falls back to defaults for unknown characters."""
    return KANJI.get(char, {
        "strokes": 0,
        "meanings": ["神秘"],
        "personality": ["独自性"],
    })
